spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_chapter04?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    #Hibernate ddl auto
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect